# Generated by Django 3.2.7 on 2021-09-18 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0002_alter_fcuser_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fcuser',
            options={'verbose_name': '패스크캠퍼스 사용자', 'verbose_name_plural': '패스크캠퍼스 사용자'},
        ),
        migrations.AddField(
            model_name='fcuser',
            name='useremail',
            field=models.EmailField(max_length=128, null=True, verbose_name='사용자 이메일'),
        ),
    ]
